# Generated by Django 4.2.17 on 2024-12-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookListAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='inventory',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
