# Generated by Django 5.1.4 on 2025-01-01 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0002_alter_menuitem_category_alter_menuitem_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menuitem', to='LittleLemonDRF.category'),
        ),
    ]
